project:
  type: website

website:
  title: "vstraining"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - materials/setup.qmd
      - text: Materials
        menu: 
          - href: materials/pre-training/index.qmd
            text: "Intro to R, RStudio, Git and GitHub"

format:
  html:
    theme: litera
    css: styles.css
    toc: true

